create table app_users (
  id varchar(64) not null,
  name varchar(120) not null,
  email varchar(180) not null,
  password_hash varchar(255) not null,
  university varchar(140) not null,
  program varchar(140) not null,
  academic_level varchar(80) not null,
  role varchar(20) not null,
  primary key (id)
);

create unique index idx_app_users_email on app_users (email);

create table courses (
  id varchar(64) not null,
  course_name varchar(140) not null,
  lecturer varchar(120) not null,
  certainty integer not null,
  base_score integer not null,
  display_order integer not null,
  primary key (id)
);

create index idx_courses_display_order on courses (display_order);

create table topic_predictions (
  id bigint generated by default as identity,
  course_id varchar(64) not null,
  display_order integer not null,
  topic varchar(140) not null,
  likelihood integer not null,
  weight varchar(30) not null,
  recommended_action varchar(300) not null,
  primary key (id),
  constraint fk_topic_predictions_course
    foreign key (course_id) references courses (id)
);

create index idx_topic_predictions_course_order on topic_predictions (course_id, display_order);

create table course_enrollments (
  id bigint generated by default as identity,
  user_id varchar(64) not null,
  course_id varchar(64) not null,
  created_at timestamp with time zone not null,
  primary key (id),
  constraint fk_course_enrollments_user
    foreign key (user_id) references app_users (id),
  constraint fk_course_enrollments_course
    foreign key (course_id) references courses (id),
  constraint uk_course_enrollments_user_course
    unique (user_id, course_id)
);

create index idx_course_enrollments_user on course_enrollments (user_id);
create index idx_course_enrollments_course on course_enrollments (course_id);

create table study_tasks (
  id varchar(80) not null,
  user_id varchar(64) not null,
  scheduled_time time not null,
  tag varchar(50) not null,
  course varchar(140) not null,
  title varchar(160) not null,
  description varchar(500) not null,
  minutes integer not null,
  accent varchar(20) not null,
  priority varchar(20) not null,
  completed boolean not null,
  primary key (id),
  constraint fk_study_tasks_user
    foreign key (user_id) references app_users (id)
);

create index idx_study_tasks_user_time on study_tasks (user_id, scheduled_time);

create table flashcards (
  id varchar(80) not null,
  user_id varchar(64) not null,
  course varchar(140) not null,
  question varchar(300) not null,
  answer varchar(600) not null,
  due_in_hours integer not null,
  mastery integer not null,
  primary key (id),
  constraint fk_flashcards_user
    foreign key (user_id) references app_users (id)
);

create index idx_flashcards_user_due on flashcards (user_id, due_in_hours, id);

create table feed_signals (
  id varchar(80) not null,
  created_by_user_id varchar(64),
  icon varchar(60) not null,
  title varchar(180) not null,
  source varchar(120) not null,
  body varchar(1000) not null,
  created_at timestamp with time zone not null,
  verified boolean not null,
  primary key (id),
  constraint fk_feed_signals_created_by
    foreign key (created_by_user_id) references app_users (id)
);

create index idx_feed_signals_created_at on feed_signals (created_at desc);

create table note_packs (
  id varchar(80) not null,
  title varchar(180) not null,
  author varchar(120) not null,
  price_kes integer not null,
  rating double precision not null,
  tag varchar(40) not null,
  verified boolean not null,
  display_order integer not null,
  primary key (id)
);

create index idx_note_packs_display_order on note_packs (display_order);

create table moderation_items (
  id varchar(80) not null,
  item varchar(180) not null,
  type varchar(60) not null,
  status varchar(40) not null,
  reason varchar(300) not null,
  display_order integer not null,
  primary key (id)
);

create index idx_moderation_items_display_order on moderation_items (display_order);

create table payment_attempts (
  checkout_request_id varchar(80) not null,
  user_id varchar(64),
  phone_number varchar(40) not null,
  amount_kes integer not null,
  reference varchar(180) not null,
  status varchar(40) not null,
  customer_message varchar(300) not null,
  created_at timestamp with time zone not null,
  primary key (checkout_request_id),
  constraint fk_payment_attempts_user
    foreign key (user_id) references app_users (id)
);

create index idx_payment_attempts_user_created_at on payment_attempts (user_id, created_at);
