create table if not exists course_enrollments (
  id bigint generated by default as identity,
  user_id varchar(64) not null,
  course_id varchar(64) not null,
  created_at timestamp with time zone not null,
  primary key (id),
  constraint fk_course_enrollments_user
    foreign key (user_id) references app_users (id),
  constraint fk_course_enrollments_course
    foreign key (course_id) references courses (id),
  constraint uk_course_enrollments_user_course
    unique (user_id, course_id)
);

create index if not exists idx_course_enrollments_user on course_enrollments (user_id);
create index if not exists idx_course_enrollments_course on course_enrollments (course_id);
