create table academic_paths (
  id varchar(64) not null,
  category varchar(60) not null,
  title varchar(180) not null,
  provider_name varchar(160) not null,
  duration_label varchar(80) not null,
  description varchar(1200) not null,
  entry_requirements varchar(800) not null,
  structure_label varchar(160),
  career_outcomes varchar(1200),
  difficulty_level varchar(40) not null,
  tags varchar(500),
  custom_track boolean not null,
  active boolean not null,
  display_order integer not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (id)
);

create index idx_academic_paths_category_order on academic_paths (category, display_order);
create index idx_academic_paths_active_order on academic_paths (active, display_order);

create table academic_modules (
  id bigint generated by default as identity,
  path_id varchar(64) not null,
  title varchar(180) not null,
  summary varchar(800) not null,
  stage_type varchar(40) not null,
  stage_label varchar(120) not null,
  display_order integer not null,
  primary key (id),
  constraint fk_academic_modules_path
    foreign key (path_id) references academic_paths (id)
);

create index idx_academic_modules_path_order on academic_modules (path_id, display_order);

create table academic_resources (
  id bigint generated by default as identity,
  path_id varchar(64) not null,
  module_id bigint,
  uploaded_by_user_id varchar(64),
  title varchar(180) not null,
  resource_type varchar(40) not null,
  description varchar(500),
  external_url varchar(500),
  original_filename varchar(255),
  storage_path varchar(500),
  content_type varchar(120),
  size_bytes bigint not null,
  display_order integer not null,
  created_at timestamp with time zone not null,
  primary key (id),
  constraint fk_academic_resources_path
    foreign key (path_id) references academic_paths (id),
  constraint fk_academic_resources_module
    foreign key (module_id) references academic_modules (id),
  constraint fk_academic_resources_uploaded_by
    foreign key (uploaded_by_user_id) references app_users (id)
);

create index idx_academic_resources_path_order on academic_resources (path_id, display_order);

create table planner_profiles (
  user_id varchar(64) not null,
  academic_path_id varchar(64),
  institution_name varchar(160) not null,
  learning_path_title varchar(180) not null,
  available_hours_per_day integer not null,
  weak_subjects varchar(600),
  strong_subjects varchar(600),
  preferred_study_times varchar(240),
  urgency_mode boolean not null,
  calendar_connected boolean not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  primary key (user_id),
  constraint fk_planner_profiles_user
    foreign key (user_id) references app_users (id),
  constraint fk_planner_profiles_path
    foreign key (academic_path_id) references academic_paths (id)
);

create table planner_milestones (
  id bigint generated by default as identity,
  user_id varchar(64) not null,
  milestone_type varchar(40) not null,
  title varchar(180) not null,
  subject_name varchar(180),
  due_at timestamp not null,
  priority varchar(20) not null,
  completed boolean not null,
  primary key (id),
  constraint fk_planner_milestones_profile
    foreign key (user_id) references planner_profiles (user_id)
);

create index idx_planner_milestones_user_due on planner_milestones (user_id, due_at);

create table planner_sessions (
  id varchar(80) not null,
  user_id varchar(64) not null,
  session_date date not null,
  scheduled_time time not null,
  tag varchar(50) not null,
  course varchar(180) not null,
  title varchar(180) not null,
  description varchar(500) not null,
  minutes integer not null,
  priority varchar(20) not null,
  accent varchar(20) not null,
  completed boolean not null,
  rescheduled boolean not null,
  created_at timestamp with time zone not null,
  primary key (id),
  constraint fk_planner_sessions_profile
    foreign key (user_id) references planner_profiles (user_id)
);

create index idx_planner_sessions_user_date_time on planner_sessions (user_id, session_date, scheduled_time);
